#!/bin/bash

#
# Mike Grozak <mike.grozak@gmail.com>
#
# - disablerepo
#   required - no
#   Repoid of repositories to disable for the install/update operation. These repos will not persist beyond the transaction. Multiple repos separated with a ',' (added in Ansible 0.9).
# - enablerepo
#   required: no
#   Repoid of repositories to enable for the install/update operation. These repos will not persist beyond the transaction multiple repos separated with a ',' (added in Ansible 0.9)
# - name
#   requried: yes
#   Package name, or package specifier with version, like name-1.0.
# - state
#   required: no
#   default: present	
#   choices: present latest absent
#   Whether to install (present, latest), or remove (absent) a package.

set -x

source ${1}

FAILED=no
YUM_REPOS=/etc/yum.repos.d

# Check the correctness of the input first

if [[ -z "${name}" ]]; then
  echo "failed=\"True\" msg=\"Please, specify the name of the package to deal with\""
  exit 5
fi

case $state in
  'present'|'latest'|'absent')
    ;;
  '')
    state="present"
    ;;
  *)
    echo "failed=\"True\" msg=\"Please, specify the correct state: present, absent or latest\""
    exit 5
    ;;
esac

if [[ ! -z "${enablerepo}" || ! -z "${disablerepo}" ]]; then
  for i in ${enablerepo//,/ } ${disablerepo//,/ }
  do
    if ! grep -q "\[$i\]" $YUM_REPOS/*.repo; then
      FAILED=yes
      failed_repos="$failed_repos $i"
    fi
  done

  if [[ ${FAILED} == "yes" ]]; then
    echo "failed=\"True\" msg=\"The following repos could not be found in yum configuration in $YUM_REPOS directory:${failed_repos}\""
    exit 4
  fi
fi

# Do the actions, finally

if [[ ! -z ${name} ]]; then
  name=${name//,/ }
fi

cmd="yum -q -y"

[[ ! -z "${enablerepo}" && ${state} != "absent" ]] && cmd="$cmd --enablerepo=${enablerepo}"
[[ ! -z "${disablerepo}" && ${state} != "absent" ]] && cmd="$cmd --disablerepo=${disablerepo}"

case ${state} in
  'present')
    # collect the names of the packages to install - do not install already installed
    for i in ${name}
    do
      ! rpmquery --quiet $i && to_install="${to_install} ${i}"
    done 

    if [[ ! -z "${to_install}" ]]; then
      cmd="${cmd} install"

      if ${cmd} ${to_install} 2>&1 &>/dev/null; then
        changed="True"
      fi
    fi
    ;;

  'latest')
    # Collect the packages to install/update first
    for i in ${name}
    do
      if ! rpmquery --quiet $i; then
        to_install="${to_install} $i"
      else
        to_update="${to_update} $i"
      fi
    done

    # install/update packages
    if [[ ! -z "${to_install}" ]]; then
      cmd1="${cmd} install"

      if ${cmd1} ${to_install} 2>&1 &>/dev/null; then
        changed="True"
      fi
    fi

    if [[ ! -z "${to_update}" ]]; then
      cmd2="${cmd} update"

      version="$(rpmquery --queryformat=\"%{VERSION}-%{RELEASE}\" ${to_update})"

      if ${cmd2} ${to_update} 2>&1 &>/dev/null; then
        version_now="$(rpmquery --queryformat=\"%{VERSION}-%{RELEASE}\" ${to_update})"

        [[ "${version}" != "${version_now}" ]] && changed="True"
      fi
    fi
    ;;

  'absent')
    to_remove=''

    for i in ${name}
    do
      rpmquery --quiet $i && to_remove="${to_remove} $i"
    done

    if [[ ! -z "${to_remove}" ]]; then
      cmd="$cmd remove"
      ${cmd} ${to_remove} 2>&1 &>/dev/null && changed="True"
    fi
    ;;
esac

[[ -z "${msg}" ]] && msg="OK"
[[ -z "${changed}" ]] && changed="False"

echo "msg=\"${msg}\" changed=\"${changed}\""

